### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by motoleon** [rtcvb32/slax#1]
Hi. When i run your script, does error:
/bin/bash^M: bad interpreter: No such file or directory

I resoved with dos2unix command, so I continued to run script:
-------------- ERROR -----------------------------
write_xattr: failed to write xattr security.capability for file /tmp/sb/01-core.sb/usr/bin/ping ....

ignoring xattrs in filesystem

run does not stop:

Extracting: 02-xorg.sb
...
...
---------------- ERROR ----------------------------
write_file: failed to create file /tmp/sb/05-chromium.sb/root/.wh..fluxbox, because Operation not permitted

run dows not stop:

Repacking: 01...
...
...
coping....
rebotting....
--------------------------------------------
run ok.  But speed no changes so much...its on usb pendrive. i will test it more time.
Its on Slax 10.8 32bit.

**Comment by rtcvb32** [comment]
I ended up copyign the script and updating it within github, it's possible it added the \r characters, dos2unix would certainly remove those characters.

I'd also only tested this on the 9.11 _stable_ version of slax. I'll download the 32bit & Beta versions and run it as well to test against.

Recompressing with lzo should add about 100Mb to the size. Might verify that, if not the workaround would be to have it skip the mv/move operation before reboot, and then replace the files if they didn't update correctly. That or use the sb2lzo scripts to recompress the files without the need to reboot (_Though it won't add the lzo versions of the scripts_)

 If memory is an issue i could leave the tmp space mostly untouched and do one directory at a time. Not my preferred method.

 Lastly the chromium 2 files i had errors on, but they look like bookmark/extra information and not neccesary for Chromium to work. Though if i redo the script to work around that it might not error anymore.

**Comment by rtcvb32** [comment]
Alright ran the script on 10.9 and it only extracted the 01-core.sb and nothing else.  This would be why you didn't get a speedup because the decompression/usage of basic utils are decompresesd during bootup and probably rarely touched or cached. The majority of speedup would be probably from apps, x-org and desktop (_probably_).

With this in mind I'll do a no-extract version that won't care which bundles you have nor the numbers (_since 07 becomes chromium rather than 06 and 06 is vlc in 10.9_), it also won't touch the /tmp and eat up more than just mksquashfs. sb2lzo probably I'll probably disable sb2dir usage.

**Comment by rtcvb32** [comment]
I've updated the scripts, which no longer extracts, works on the 10.9 and 10.8, and ran it on the 32bit version as well and it seems to be working fine.

It won't unpack any longer and instead pack mounted bundles saving them directly to the device you point to. This should save on memory for more limited machines, but i can't say how much it will use, probably not that much.

Since i can't add/change the filesystems now 01-lzo.sb is created with the lzo scripts and touch-to-tap.

Also if you Ctrl+C before 'move and reboot' you can inturrupt the script and inspect the sb files.

sb2lzo is also updated and works where it mounts and recompresses, no uncompressing and wasted space.

I hope that solves all the problems.

**Comment by rtcvb32** [comment]
hmmm probably shouldn't close until i get feedback...

**Comment by motoleon** [comment]
Ok. Many thanks for your efford.

**Comment by rtcvb32** [comment]
Did it work for you? Any comments?

**Comment by rtcvb32** [comment]
> Ok. Many thanks for your efford.

Did it work for you then? Any additional comments?
